### ISSUE TITLE
Post call does not follow promise catch convention upon error?

### ISSUE THREAD

**Issue by cdichiara** [lukasolson/fitbit-node#19]
Hi, I believe this is something that could be improved upon:

```
2017-09-16T04:34:47.760Z	5ed2f788-9a98-11e7-9724-fd7f1e43e31c	CDC-REMOVE: Result of fitbit.post: [
{
    "errors": [
        {
            "errorType": "insufficient_permissions",
            "message": "API client is not authorized by the resource owner to access the resource requested. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process."
        }
    ],
    "success": false
}
,
{
    "statusCode": 403,
    "body": {
        "errors": [
            {
                "errorType": "insufficient_permissions",
                "message": "API client is not authorized by the resource owner to access the resource requested. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process."
            }
        ],
        "success": false
    },
 // etc
}
]
```

You're returning errors as a resolved promise, not a rejected one.

**Comment by jmdiego** [comment]
@cdichiara this is the way "request" (which the module depends on) handles error responses, the catch will occur when the host is not responding, there is no internet connection, etc. but all of the server handled errors are resolved and the detail of the error is provided in the data, otherwise the information about the error would be limited to the error code, a message and the stack trace.

**Comment by cdichiara** [comment]
OK, got it ... I couldn't tell from your documentation what you were returning on either success or failure. Over here I've just been subclassing Error to add more information.
