### ISSUE TITLE
calling getRefreshToken throws a 400 error

### ISSUE THREAD

**Issue by ldeluca** [lukasolson/fitbit-node#7]
When I call the refreshAccesstoken method with a valid refreshToken:

client.refreshAccesstoken(req.body.refreshToken).then(function (result) {
                 console.log("BACK FROM REFRESHACCESSTOKEN" + JSON.stringify(result));
             }).catch(function (error) {
        console.error('problems getting refresh token: ' + JSON.stringify(error));
        res.send(error);
    });

I see the following error:

problems getting refresh token: {"name":"Error","status":400,"message":"Bad Request","context":{"errors":[{"errorType":"invalid_request","message":"Missing parameters: refresh_token Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process."}],"success":false}}

**Comment by mbmccormick** [comment]
Sorry about that, looks like the README was out of date. I fixed that in f223d5a5be89a01fb66678786e2499532f0eee48. You need to pass both the expired access token AND the refresh token in order to refresh the access token:

`refreshAccesstoken(accessToken, refreshToken, [expiresIn])`

I have a [full example](https://github.com/mbmccormick/fitminder/blob/2e4c9deac0518f2308809290cb99bf5564e3365d/app/fitbit.js#L10) on my Fitminder application.
